### PR TITLE
Fix yaml warnings

### PR DESCRIPTION
**Pull request by MarkusPrim**
Fixes Issue #85

Get rid of the deprecration warning explained here:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

The fix is minimal invasive. It explicitly performes what is done implicitly up until now, getting rid of the warning. When you run the tests now, there is still one yaml warning left from the wcxf package. I will create a pull request there to fix the issue.

Cheers,
Markus

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Perfect, thanks!

**Comment by DavidMStraub** [comment]
I now realized that `yaml.FullLoader` is actually not defined in prior versions of PyYAML. This makes this fix not backward compatible. While this could be worked around by forcing the new PyYAML version as a dependency, I think this is problematic as many packages now seem to pin the dependency to the *old* PyYAML version to avoid breakages. So I decided to simply replace `load` by `safe_load` everywhere. This should get rid of the warning with PyYAML 5.1, but also work with the old version 3.12. I implemented this in 8e1d05a8ed2e72bb51ab18efff7fa558f20c4ddf.

**Comment by MarkusPrim** [comment]
@DavidMStraub Woops. I did not check for this but relied on the integration build instead. Sorry!

**Comment by DavidMStraub** [comment]
No problem!
I just applied the same fix in wcxf: 413eeb7ede8e8141a37dedd8fc24262b332890bb

**Pull request merged**
