### PR TITLE
Dump wc fit function

### PR DESCRIPTION
**Pull request by peterstangl**
@DavidMStraub this is a first working implementation. However, some things might be done more elegantly, especially on how the schema is used. I'm also not completely happy with the variable name `defdict_fit_wc_function` for the defining dictionary... So suggestions and changes are welcome!

### CODE REVIEW

**Comment by DavidMStraub** [comment]
A problem with this is that it changes the interface of the `Fit` subclasses without any real benefit (the `defdict...` is only useful in connection with the `load` feature, the user otherwise doesn't need to know about it). The number of arguments is already too high. And I would keep the `fit_wc_function` a function.

What about simply

```python
 def load(cls, f):
    kwargs = cls._input_schema(flavio.io.yaml.load_include(f))
    fit = cls(**kwargs)
    if 'fit_wc_function' in kwargs:
        fit._fit_wc_function_string = kwargs['fit_wc_function']
    return fit
```

**Comment by DavidMStraub** [comment]
Correction: one needs to call the `wc_function_factory` in `load` as well (after saving the string to the private attribute).

**Comment by peterstangl** [comment]
Yes, you are completely right. It is a much cleaner solution to put everything in the `load` and `dump` methods and to not change `__init__` at all.

**Comment by DavidMStraub** [comment]
This can be merged now, right?

I still don't quite understand why the `'code'` isn't just taken as-is. The splitting and joining seems a bit hacky. Why should the user be forced to provide both a `def` and `'args'`?

**Comment by peterstangl** [comment]
I don't understand why you write that the user is forced to provide `def` and `'args'`. The user just provides a string with the definition of the function.
If the `code` is taken as-is, the function name of the `fit_wc_function` is defined in the YAML file and this name is arbitrary. After executing the code, this results in defining a function with an unknown name (as long as the name is not retrieved somehow). This means that the `return f` later in the code does not work in general if the function's name is not `f`. The splitting and joining changes the input string such that the name of the function is forced to be `f`.
I admit that this is a bit hacky. Do you know a better solution? E.g. do you know how the function name can be retrieved after defining it using `exec`?

**Comment by peterstangl** [comment]
If one keeps the renaming the function, this could perhaps also be done more elegantly using regex instead of splitting and joining.

**Comment by DavidMStraub** [comment]
Sorry, you're right.

OK if it's just about the renaming I think it's better to force the user to name the function `f`.

**Pull request merged**
